addons:
    apt:
        packages:
            - texlive-binaries
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-luatex
            - xzdec

branches:
    only:
        - master
        - staging
        - trying
        - /^release\/.*$/ # release branches
        - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: bash

latex: true

matrix:
    fast_finish: true

notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always

os:
    - linux
    
sudo: required

# ===========================================================================

before_install:
    - sudo tlmgr init-usertree
    - sudo tlmgr install luatex
    - sudo tlmgr install lualatex
    - sudo tlmgr install biblatex
    - sudo tlmgr install biber
    - sudo tlmgr install l3build
install:
    - true
before_script:
    - true
script:
    - ./ci/travis/script.sh
after_script:
- true
